theme: jekyll-theme-dinky
title: Welcome to my data science portfolio
description: Here you will find projects from my master's program, personal projects and submissions for online competitions. Have a look at the README for a further introduction of myself.
